// Comprehensive Rich Heritage Sites with In-Depth Historical Narratives,
// The Hidden Aspect (Secret chambers/tunnels/acoustics), Timings, Crowd Density,
// Dress Code, Reviews, Google Maps Links, Scam Alerts & Safety Precautions.
// Sourced from Ministry of Tourism & The Cyclopedic Registry of AP & Telangana

export const enrichedHeritageSites = [
  // --- 1. VISAKHAPATNAM & NORTH COASTAL AP ---
  {
    id: "borra-caves",
    name: "Borra Caves & Subterranean River",
    state: "Andhra Pradesh",
    district: "Visakhapatnam / Alluri Sitharama Raju",
    city: "Visakhapatnam",
    tag: "caves",
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Borra_caves_1.jpg",
    description: "Million-year-old karstic limestone caves at 1400m altitude in Ananthagiri Hills, pierced by the sacred Gosthani River.",
    historicalNarrative: "Formed over a million years ago by the flowing waters of the Gosthani River cutting through karstic limestone deposits. Discovered scientifically by William King of the Geological Survey of India in 1807, though tribal communities have revered the naturally formed Shiva Lingam stalagmite for millennia.",
    hiddenAspect: "A subterranean tunnel network extending deeper beneath the illuminated tourist pathways contains prehistoric Paleolithic stone implements and unmapped acoustic caverns with natural resonant frequencies.",
    timings: "10:00 AM - 05:00 PM (Lunch break: 01:00 PM - 02:00 PM)",
    crowdDensity: "High on weekends & holidays; Moderate on weekday mornings",
    dressCode: "Comfortable trekking shoes with grip (slippery cavern floor); light breathable cotton wear",
    rating: 4.7,
    reviewsCount: 3890,
    reviews: [
      { user: "Kiran R.", rating: 5, comment: "The LED lighting inside illuminates natural stalactites shaped like Rishi skulls and Mother-Child. Must-visit near Araku!" },
      { user: "Pooja M.", rating: 4, comment: "Breathtaking natural formation. Walk down 300 steps is steep, take it easy if traveling with seniors." }
    ],
    address: "Ananthagiri Hills, Araku Valley road, Visakhapatnam District, Andhra Pradesh 535145",
    lat: 18.2811,
    lng: 83.0392,
    wiki: "https://en.wikipedia.org/wiki/Borra_Caves",
    youtube: "https://www.youtube.com/results?search_query=borra+caves+documentary",
    mapsUrl: "https://maps.google.com/?q=Borra+Caves+Andhra+Pradesh",
    frequentScams: "Unauthorized vendors outside selling fake 'healing cave gemstones' and illegal bamboo shoot powders at inflated prices. Buy entry tickets only at official APTDC counters.",
    safetyTips: "Cave steps can be slippery due to subterranean moisture. Elders should use handrails. Mobile network (Jio/Airtel) is weak inside the cave interior."
  },
  {
    id: "thotlakonda-buddhist-complex",
    name: "Thotlakonda & Bavikonda Buddhist Monasteries",
    state: "Andhra Pradesh",
    district: "Visakhapatnam",
    city: "Visakhapatnam",
    tag: "ruins",
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Viharas_in_Thotlakonda%2C_Visakhapatnam.jpg",
    description: "2000-year-old Hinayana Buddhist monastic hill complex commanding dramatic 360-degree views of the Bay of Bengal.",
    historicalNarrative: "Thotlakonda ('Hill of Stone Cisterns') flourished between the 2nd Century BCE and 2nd Century CE during the Satavahana era. It served as a premier maritime Buddhist monastery welcoming sea-traders and monks voyaging across Southeast Asia, Sri Lanka, and Rome.",
    hiddenAspect: "Rock-cut rainwater harvesting cisterns interconnected by subterranean filtration pipes, and unexcavated votive stupas facing the Roman maritime trade routes on the sea horizon.",
    timings: "09:00 AM - 05:30 PM (All days)",
    crowdDensity: "Low to Moderate; peaceful and quiet",
    dressCode: "Respectful attire; shoes must be removed when entering designated stupa plinths",
    rating: 4.6,
    reviewsCount: 1420,
    reviews: [
      { user: "Siddharth V.", rating: 5, comment: "Perched high on the hill with oceanic breeze. The ancient stone cisterns and stupa platforms are awe-inspiring." }
    ],
    address: "Bheemunipatnam Beach Road, Mangamaripeta, Visakhapatnam, Andhra Pradesh 530048",
    lat: 17.8252,
    lng: 83.4158,
    wiki: "https://en.wikipedia.org/wiki/Thotlakonda",
    youtube: "https://www.youtube.com/results?search_query=thotlakonda+buddhist+complex",
    mapsUrl: "https://maps.google.com/?q=Thotlakonda+Buddhist+Complex+Visakhapatnam",
    frequentScams: "Unregistered freelance 'archaeologists' offering fake antique coins or asking donations for unregistered monastery trusts. No payment is needed beyond official ticket gate.",
    safetyTips: "Carry bottled drinking water and umbrella as hilltop is exposed to coastal sun. Strict safety barriers exist along cliff edges."
  },
  {
    id: "simhachalam-temple",
    name: "Sri Varaha Lakshmi Narasimha Temple (Simhachalam)",
    state: "Andhra Pradesh",
    district: "Visakhapatnam",
    city: "Visakhapatnam",
    tag: "temple",
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Simhachalam_inner_temple_architecture.jpg",
    description: "11th-century Kalinga-style architectural marvel where Lord Narasimha is covered continuously in sacred sandalwood paste.",
    historicalNarrative: "Built by Eastern Ganga king Narasimhadeva I (the builder of Konark Sun Temple) in the 13th century on an 11th-century foundation. Over 500 inscriptions in Telugu and Oriya chronicle endowments from Chola, Kakatiya, and Vijayanagara monarchs like Sri Krishnadevaraya.",
    hiddenAspect: "The sanctum sanctorum houses an ancient subterranean spring feeding the stepped Kalyani tank, and an enclosed 16-pillared Natya Mandapam with intricate musical stone pillars that resonate distinct pitches.",
    timings: "07:00 AM - 04:00 PM & 06:00 PM - 09:00 PM (Chandanotsavam annual festival in May)",
    crowdDensity: "Very High on weekends and festivals; Moderate on weekday mornings",
    dressCode: "Traditional Hindu dress strictly enforced: Dhotis/Kurta-Pajama for men; Sarees/Salwar Kameez for women. No western shorts.",
    rating: 4.8,
    reviewsCount: 6500,
    reviews: [
      { user: "Venkatesh P.", rating: 5, comment: "Spiritual aura is unmatched. The Kalinga stone carvings on the outer circumambulatory corridor are museum quality." }
    ],
    address: "Simhachalam Hill, Visakhapatnam, Andhra Pradesh 530028",
    lat: 17.7667,
    lng: 83.2505,
    wiki: "https://en.wikipedia.org/wiki/Varaha_Lakshmi_Narasimha_temple,_Simhachalam",
    youtube: "https://www.youtube.com/results?search_query=simhachalam+temple+history",
    mapsUrl: "https://maps.google.com/?q=Simhachalam+Temple+Visakhapatnam",
    frequentScams: "Touts offering 'instant special darshan VIP bypass' outside ghat road. Only purchase authenticated Devasthanam VIP tickets inside the official Devasthanam administrative office counters.",
    safetyTips: "Free cloakroom available for mobile phones and footwear. Winding ghat road requires careful driving or official Devasthanam electric bus shuttle."
  },

  // --- 2. TELANGANA ROYAL & HISTORICAL MARVELS ---
  {
    id: "golconda-fort",
    name: "Golconda Fort & Acoustic Whispering Citadel",
    state: "Telangana",
    district: "Hyderabad",
    city: "Hyderabad",
    tag: "monument",
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Golconda_fort.jpg",
    description: "Magnificent 16th-century diamond capital citadel with phenomenal acoustics where a hand-clap at the grand gate echoes atop the Bala Hissar.",
    historicalNarrative: "Originally a mud fort constructed by the Kakatiya rulers in the 12th century, it was fortified by the Qutb Shahi dynasty from 1518 to 1687 into an impregnable citadel. Renowned worldwide as the trade vault of the Koh-i-Noor, Hope, and Daria-i-Noor diamonds.",
    hiddenAspect: "A legendary subterranean escape tunnel connects the Durbar Hall directly to the royal Qutb Shahi tombs and Charminar 8 km away. The acoustic engineering at the Fateh Darwaza is designed to transmit military alerts to the hilltop without electronic amplification.",
    timings: "09:00 AM - 05:30 PM (Sound & Light Show: 06:30 PM - 08:30 PM)",
    crowdDensity: "High in late afternoons and during evening Sound & Light show",
    dressCode: "Comfortable walking shoes (steep stone ramps and 380 stairs to Bala Hissar summit)",
    rating: 4.8,
    reviewsCount: 12400,
    reviews: [
      { user: "Farhan A.", rating: 5, comment: "Clapped under the dome at the entrance and my brother heard it clearly on the hilltop 1 km away! Sheer architectural genius." }
    ],
    address: "Ibrahim Bagh, Hyderabad, Telangana 500008",
    lat: 17.3833,
    lng: 78.4011,
    wiki: "https://en.wikipedia.org/wiki/Golconda",
    youtube: "https://www.youtube.com/results?search_query=golconda+fort+acoustics",
    mapsUrl: "https://maps.google.com/?q=Golconda+Fort+Hyderabad",
    frequentScams: "Uncertified guides standing near parking lots claiming ASI credentials. Check for official ASI holographic photo badge pinned to their shirt.",
    safetyTips: "Stay hydrated. Avoid climbing unlit parapet walls after sunset. Secure personal belongings in crowded bazaars nearby."
  },
  {
    id: "charminar",
    name: "Charminar & Historic Laad Bazaar",
    state: "Telangana",
    district: "Hyderabad",
    city: "Hyderabad",
    tag: "monument",
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Charminar_Hyderabad_1.jpg",
    description: "Four-minareted grand monument built in 1591 by Muhammad Quli Qutb Shah surrounded by world-famous pearl and lacquer bangle markets.",
    historicalNarrative: "Commissioned in 1591 to commemorate the eradication of a devastating plague and to mark the intersection of historic trade routes between Golconda and Machilipatnam port. The second floor features the oldest mosque in Hyderabad.",
    hiddenAspect: "The four spiral staircases with 149 steps conceal hidden acoustic vent holes that allowed guards to overhear whispers on the street beneath.",
    timings: "09:30 AM - 05:30 PM (Surrounding bazaar open until 11:00 PM)",
    crowdDensity: "Very High in evenings and festive periods (Ramzan, Diwali)",
    dressCode: "Modest casual attire; respectful dress for upper mosque level",
    rating: 4.7,
    reviewsCount: 18900,
    reviews: [
      { user: "Ayesha S.", rating: 5, comment: "The heart and soul of Hyderabad. Irani chai and Osmania biscuits at Nimrah Cafe right opposite Charminar is a must!" }
    ],
    address: "Charminar Rd, Char Kaman, Ghansi Bazaar, Hyderabad, Telangana 500002",
    lat: 17.3616,
    lng: 78.4747,
    wiki: "https://en.wikipedia.org/wiki/Charminar",
    youtube: "https://www.youtube.com/results?search_query=charminar+hyderabad+history",
    mapsUrl: "https://maps.google.com/?q=Charminar+Hyderabad",
    frequentScams: "Street vendors selling synthetic plastic beads as 'authentic Hyderabadi Basra pearls'. Purchase pearls only from certified BIS hallmarked jeweler showrooms with certificate.",
    safetyTips: "Keep wallet and phone in front zip pockets in crowded alleys of Laad Bazaar. Pedestrian plaza is clean and patrolled by tourist police."
  },
  {
    id: "ramappa-temple",
    name: "Kakatiya Rudreshwara (Ramappa) Temple (UNESCO World Heritage)",
    state: "Telangana",
    district: "Mulugu",
    city: "Warangal",
    tag: "temple",
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Ramappa_Temple_(Human_Scale).jpg",
    description: "UNESCO World Heritage Site renowned for floating porous bricks, sandbox earthquake-resistant foundation, and mirror-polished black basalt bracket dancer sculptures.",
    historicalNarrative: "Constructed in 1213 CE under Kakatiya general Recharla Rudra during the reign of Ganapati Deva. The only temple in India named after its sculptor-architect, Ramappa, who laboured 40 years to complete its ethereal details.",
    hiddenAspect: "The superstructure spires were built using lightweight 'floating bricks' made from spongy sawdust-clay composition that float on water. The foundations use deep sandbox technology that survived major medieval earthquakes without structural cracks.",
    timings: "06:00 AM - 06:00 PM",
    crowdDensity: "Moderate on weekends; Serene on weekdays",
    dressCode: "Traditional decent attire; footwear removed at entrance",
    rating: 4.9,
    reviewsCount: 4200,
    reviews: [
      { user: "Dr. K. Sastri", rating: 5, comment: "The mirror finish on the basalt dancer brackets (Madanikas) is so smooth you can see your reflection! A world wonder of Kakatiya engineering." }
    ],
    address: "Palampet Village, Venkatapur Mandal, Mulugu District, Telangana 506345",
    lat: 18.2612,
    lng: 79.9431,
    wiki: "https://en.wikipedia.org/wiki/Ramappa_Temple",
    youtube: "https://www.youtube.com/results?search_query=ramappa+temple+floating+bricks",
    mapsUrl: "https://maps.google.com/?q=Ramappa+Temple+Telangana",
    frequentScams: "Unauthorized parking agents along the access road demanding ₹100 instead of the standard ₹20-30 government fee.",
    safetyTips: "Stay on marked stone pathways. Enjoy the sunset over adjacent Ramappa Lake."
  },

  // --- 3. TIRUPATI & SOUTHERN AP ---
  {
    id: "tirumala-venkateswara",
    name: "Sri Venkateswara Swamy Temple (Tirumala)",
    state: "Andhra Pradesh",
    district: "Tirupati",
    city: "Tirupati",
    tag: "temple",
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Tirumala_temple.JPG",
    description: "The world's most visited sacred pilgrimage shrine perched on the sacred Seshachalam Seven Hills of Tirumala.",
    historicalNarrative: "Mentioned in the Rigveda and Sangam literature, and patronized by the Pallavas, Cholas, Pandyas, and most famously King Krishnadevaraya of Vijayanagara, who donated pure gold for the Ananda Nilayam vimana roof.",
    hiddenAspect: "Behind the sanctum sanctorum lies a subterranean fresh water source known as Viraja River pool. The sacred murti of Lord Venkateswara is said to stay naturally at 43°C body temperature despite cool hill climate.",
    timings: "03:00 AM - 11:30 PM (Vaikunta Darshanam / Suprabhatam per TTD schedule)",
    crowdDensity: "Extremely High (60,000 to 100,000 pilgrims daily)",
    dressCode: "Strict TTD Dress Code: Men: White Dhoti/Pancha with shirt or Angavastram. Women: Traditional Saree or Half-Saree or Salwar with Dupatta.",
    rating: 4.9,
    reviewsCount: 35000,
    reviews: [
      { user: "Rajesh K.", rating: 5, comment: "Govinda! Govinda! The energy inside Ananda Nilayam cannot be described in words. The sacred Tirupati Laddu Prasadam is divine." }
    ],
    address: "S Mada St, Tirumala, Tirupati, Andhra Pradesh 517504",
    lat: 13.6833,
    lng: 79.3500,
    wiki: "https://en.wikipedia.org/wiki/Venkateswara_Temple,_Tirumala",
    youtube: "https://www.youtube.com/results?search_query=tirumala+temple+history",
    mapsUrl: "https://maps.google.com/?q=Tirumala+Venkateswara+Temple+Tirupati",
    frequentScams: "Fake online ticket websites mimicking the official TTD portal. Only book on the verified official domain: tirupatibalaji.ap.gov.in. Beware touts promising 'guaranteed 10-minute darshan'.",
    safetyTips: "Pre-book SED (Special Entry Darshan) ₹300 tickets online months in advance. Wear thermal layers if ascending by pedestrian footpaths (Alipiri or Srivari Mettu) at night."
  },
  {
    id: "lepakshi-veerabhadra",
    name: "Lepakshi Veerabhadra Temple & Hanging Pillar",
    state: "Andhra Pradesh",
    district: "Sri Sathya Sai / Anantapur",
    city: "Lepakshi",
    tag: "temple",
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/The_hanging_pillar_at_Lepakshi_temple.JPG",
    description: "16th-century Vijayanagara architectural masterpiece featuring the world-famous Hanging Pillar and gigantic monolithic Nandi.",
    historicalNarrative: "Constructed in 1538 CE by royal brothers Virupanna and Veeranna under the patronage of Emperor Achyuta Deva Raya of the Vijayanagara Empire. Celebrated for grand mural frescoes of Shiva and the Ramayana painted with natural vegetable dyes.",
    hiddenAspect: "Among the 70 stone pillars in the Natya Mandapam, one famed 'Hanging Pillar' does not touch the granite floor at all; visitors can pass a thin cloth or paper underneath it freely without friction.",
    timings: "06:00 AM - 06:00 PM (Daily)",
    crowdDensity: "Moderate on weekends; Peaceful on weekdays",
    dressCode: "Modest attire; footwear must be left at outer temple gopuram",
    rating: 4.8,
    reviewsCount: 4100,
    reviews: [
      { user: "Manoj B.", rating: 5, comment: "Passed a dupatta under the hanging pillar myself! The colossal monolithic Nagalinga and monolithic Nandi 500m away are breathtaking." }
    ],
    address: "Lepakshi Village, Sri Sathya Sai District, Andhra Pradesh 515331",
    lat: 13.8034,
    lng: 77.6062,
    wiki: "https://en.wikipedia.org/wiki/Lepakshi",
    youtube: "https://www.youtube.com/results?search_query=lepakshi+hanging+pillar+secret",
    mapsUrl: "https://maps.google.com/?q=Lepakshi+Veerabhadra+Temple",
    frequentScams: "Touts offering to sell alleged 'ancient temple bronze bells' near the Nandi circle. Refuse any counterfeit antiquities.",
    safetyTips: "Granite stones become hot under bare feet around noon; visit before 10:30 AM or after 3:30 PM for comfortable walking."
  },

  // --- 4. EXPANDED ANDHRA PRADESH SITES ---
  {
    id: "kailasagiri",
    name: "Kailasagiri Hilltop Park & Panoramic Bay View",
    state: "Andhra Pradesh",
    district: "Visakhapatnam",
    city: "Visakhapatnam",
    tag: "nature",
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Shiva%2C_Parvati_statues_on_Kailasagiri_06.jpg",
    description: "Hilltop plateau 360ft above sea level overlooking Rishikonda and RK Beach with colossal 40ft Shiva-Parvathi statues and coastal ropeway.",
    historicalNarrative: "Developed as a premier coastal ecotourism hilltop overlooking the ancient maritime coast of Kalinga.",
    hiddenAspect: "A cliffside Titanic viewpoint commanding panoramic views of both the Eastern Ghats forest ranges and the Bay of Bengal coastline.",
    timings: "06:00 AM - 08:30 PM (Ropeway operational: 09:00 AM - 07:30 PM)",
    crowdDensity: "High in evenings; serene in early mornings",
    dressCode: "Comfortable casual attire",
    rating: 4.6,
    reviewsCount: 8200,
    reviews: [
      { user: "Sireesha T.", rating: 5, comment: "Ropeway ride offers the best view of Vizag city! Great toy train for kids and elders." }
    ],
    address: "Hill Top Rd, Kailasagiri, Visakhapatnam, Andhra Pradesh 530043",
    lat: 17.7490,
    lng: 83.3420,
    wiki: "https://en.wikipedia.org/wiki/Kailasagiri",
    youtube: "https://www.youtube.com/results?search_query=kailasagiri+visakhapatnam",
    mapsUrl: "https://maps.google.com/?q=Kailasagiri+Visakhapatnam",
    frequentScams: "Unapproved private photographers claiming official APTDC rates. Use your own smartphone.",
    safetyTips: "Do not climb beyond cliffside warning barriers."
  },
  {
    id: "ins-kursura",
    name: "INS Kursura Submarine Museum (RK Beach)",
    state: "Andhra Pradesh",
    district: "Visakhapatnam",
    city: "Visakhapatnam",
    tag: "monument",
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/INS_Kursura_(S20).jpg",
    description: "South Asia's first submarine museum preserved on the sands of RK Beach — a Soviet-built Kalvari-class submarine of the 1971 Indo-Pak War.",
    historicalNarrative: "Commissioned on 18 December 1969 in Riga, Soviet Union, INS Kursura played a vital patrol and intelligence role in the 1971 war.",
    hiddenAspect: "Preserved with authentic torpedo tubes, sonar rooms, periscopes, and crew bunk cabins demonstrating life underwater.",
    timings: "02:00 PM - 08:30 PM (Tuesday to Saturday); 10:00 AM - 08:30 PM (Sunday); Closed Mondays",
    crowdDensity: "High on Sunday evenings",
    dressCode: "Flat walking shoes recommended (metal ladder navigation inside hull)",
    rating: 4.8,
    reviewsCount: 11200,
    reviews: [
      { user: "Ravi Teja", rating: 5, comment: "Fascinating experience to walk through an actual submarine! The retired naval guides explain everything." }
    ],
    address: "Beach Rd, Paanduranga Puram, Visakhapatnam, Andhra Pradesh 530017",
    lat: 17.7164,
    lng: 83.3339,
    wiki: "https://en.wikipedia.org/wiki/INS_Kursura_(S20)",
    youtube: "https://www.youtube.com/results?search_query=ins+kursura+submarine+museum",
    mapsUrl: "https://maps.google.com/?q=INS+Kursura+Submarine+Museum",
    frequentScams: "Street touts selling fake entry passes outside the gate. Only purchase at the official electronic ticket counter.",
    safetyTips: "Narrow submarine bulkheads require ducking; mind your head when stepping across watertight doors."
  },
  {
    id: "araku-valley",
    name: "Araku Valley Coffee Plantations & Tribal Heritage",
    state: "Andhra Pradesh",
    district: "Alluri Sitharama Raju",
    city: "Araku",
    tag: "nature",
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Araku_valley.JPG",
    description: "Verdant misty hill station at 3,000 ft altitude renowned for organic GI-tagged Araku coffee, Dhimsa tribal dance, and Padmapuram Gardens.",
    historicalNarrative: "Inhabited by indigenous Valmiki, Bagata, and Khond tribes. Cultivates globally acclaimed shade-grown organic Arabica coffee.",
    hiddenAspect: "Traditional Dhimsa bronze bell rhythms and sacred grove herbal medicine conservation centers maintained by tribal village elders.",
    timings: "08:00 AM - 06:00 PM (Best season: October to March)",
    crowdDensity: "High on winter weekends",
    dressCode: "Warm jacket/sweater for chilly mornings and evenings",
    rating: 4.7,
    reviewsCount: 18000,
    reviews: [
      { user: "Deepika N.", rating: 5, comment: "The train journey through 58 tunnels from Vizag to Araku is magical! Pure organic coffee and fresh bamboo chicken." }
    ],
    address: "Araku Valley, Eastern Ghats, Andhra Pradesh 531149",
    lat: 18.3333,
    lng: 82.8833,
    wiki: "https://en.wikipedia.org/wiki/Araku_Valley",
    youtube: "https://www.youtube.com/results?search_query=araku+valley+tourism",
    mapsUrl: "https://maps.google.com/?q=Araku+Valley+Andhra+Pradesh",
    frequentScams: "Fake 'wild forest honey' adulterated with sugar syrup sold by highway hawkers. Buy verified Girijan Cooperative (GCC) products only.",
    safetyTips: "Ghat road has steep hairpin curves; avoid night driving during heavy mountain fog."
  },
  {
    id: "amaravati-mahachaitya",
    name: "Amaravati Mahachaitya & 125ft Dhyana Buddha",
    state: "Andhra Pradesh",
    district: "Palnadu",
    city: "Amaravati",
    tag: "temple",
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Dhyana_Buddha_statue_in_Amaravati.jpg",
    description: "Ancient Satavahana Buddhist metropolis on the Krishna River featuring the colossal 125-foot Dhyana Buddha and ASI Heritage Museum.",
    historicalNarrative: "One of the greatest centers of Buddhist learning in antiquity (2nd Century BCE - 3rd Century CE). Visited by Acharya Nagarjuna who expounded the Madhyamaka philosophy.",
    hiddenAspect: "Intricate limestone relief medallions depicting the Jataka tales, now conserved in world museums including the British Museum's Amaravati Gallery.",
    timings: "09:00 AM - 05:00 PM (Museum closed Fridays)",
    crowdDensity: "Peaceful and uncrowded",
    dressCode: "Modest attire",
    rating: 4.6,
    reviewsCount: 3100,
    reviews: [
      { user: "Anand M.", rating: 5, comment: "The gigantic 125ft Dhyana Buddha statue on Krishna River bank is awe-inspiring and serene." }
    ],
    address: "Amaravati, Palnadu District, Andhra Pradesh 522020",
    lat: 16.5744,
    lng: 80.3575,
    wiki: "https://en.wikipedia.org/wiki/Amaravati_Stupa",
    youtube: "https://www.youtube.com/results?search_query=amaravati+buddhist+stupa",
    mapsUrl: "https://maps.google.com/?q=Amaravati+Stupa+Andhra+Pradesh",
    frequentScams: "Unlicensed tour touts near riverbank. Official ASI museum tickets provide free guided maps.",
    safetyTips: "River ghats can have strong currents during monsoon."
  },
  {
    id: "undavalli-caves",
    name: "Undavalli 4-Storey Rock-Cut Caves",
    state: "Andhra Pradesh",
    district: "Guntur",
    city: "Vijayawada",
    tag: "caves",
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Undavalli_Caves_2021.jpg",
    description: "Magnificent 4th-5th century CE monolithic multi-tiered sandstone cave monastery featuring a colossal 5-meter reclining Vishnu Anantasayana sculpture.",
    historicalNarrative: "Carved during the reign of Vishnukundina monarchs (420–620 CE) on solid sandstone hillside facing the lush Krishna River green belt.",
    hiddenAspect: "Hidden rock-cut monk cells on the top tier with acoustic resonance designed for Vedic and Buddhist chanting.",
    timings: "09:00 AM - 05:30 PM (Daily)",
    crowdDensity: "Moderate on weekends",
    dressCode: "Comfortable footwear for stone staircases",
    rating: 4.7,
    reviewsCount: 5400,
    reviews: [
      { user: "Pradeep S.", rating: 5, comment: "4 storeys carved directly out of a single mountain cliff! The reclining Vishnu sculpture is grand." }
    ],
    address: "Undavalli Caves Rd, Undavalli, Andhra Pradesh 522501",
    lat: 16.4975,
    lng: 80.5814,
    wiki: "https://en.wikipedia.org/wiki/Undavalli_Caves",
    youtube: "https://www.youtube.com/results?search_query=undavalli+caves+history",
    mapsUrl: "https://maps.google.com/?q=Undavalli+Caves+Vijayawada",
    frequentScams: "Overpriced street parking. Use the official ASI designated parking lot.",
    safetyTips: "Upper stone levels have steep steps; hold safety railings."
  },

  // --- 5. EXPANDED TELANGANA SITES ---
  {
    id: "thousand-pillar-temple",
    name: "Warangal Thousand Pillar Temple (Rudreswara)",
    state: "Telangana",
    district: "Hanamkonda",
    city: "Warangal",
    tag: "temple",
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Long_View_of_1000_Pillar_Temple%2C_Warangal_Telangana.jpg",
    description: "Star-shaped 1163 CE Kakatiya triple-shrine (Trikuta) temple featuring 1,000 intricately carved monolithic basalt pillars and a 6ft monolithic Nandi.",
    historicalNarrative: "Constructed under king Rudra Deva. Dedicated to Shiva, Vishnu, and Surya. Star-shaped raised granite plinth design absorbs seismic tremors.",
    hiddenAspect: "No single pillar obstructs the view of the sanctum sanctorum from any point within the pillared hall.",
    timings: "06:00 AM - 08:00 PM (Daily)",
    crowdDensity: "Moderate; peaceful mornings",
    dressCode: "Traditional decent attire",
    rating: 4.7,
    reviewsCount: 6800,
    reviews: [
      { user: "Vamshi K.", rating: 5, comment: "The monolithic Nandi carved out of black basalt stone has an eternal mirror polish." }
    ],
    address: "Hanamkonda, Warangal, Telangana 506001",
    lat: 17.9986,
    lng: 79.5775,
    wiki: "https://en.wikipedia.org/wiki/Thousand_Pillar_Temple",
    youtube: "https://www.youtube.com/results?search_query=thousand+pillar+temple+warangal",
    mapsUrl: "https://maps.google.com/?q=Thousand+Pillar+Temple+Warangal",
    frequentScams: "Fake VIP prasad sellers near outer gate.",
    safetyTips: "Granite courtyard can get hot at noon; visit early morning or late afternoon."
  },

  // --- 6. EXPANDED NATIONAL SITES ---
  {
    id: "varanasi-ghats",
    name: "Varanasi Ghats & Sacred Ganga Aarti",
    state: "Uttar Pradesh",
    district: "Varanasi",
    city: "Varanasi",
    tag: "spiritual",
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Ganga_Aarti_at_Varanasi_ghats.jpg",
    description: "One of the world's oldest continuously inhabited sacred cities with 84 stone ghats stretching along the crescent holy Ganges.",
    historicalNarrative: "Mentioned in the Skanda Purana and Buddhist scriptures. For over 3,000 years, poets, philosophers, and seekers have gathered on these sacred steps.",
    hiddenAspect: "Submerged Shiva temple at Scindia Ghat that tilted 45 degrees into the riverbed in 1830 and remains structurally intact underwater.",
    timings: "Open 24 hours; Evening Ganga Aarti: 06:30 PM - 07:30 PM",
    crowdDensity: "Extremely High during evening aarti and Kartik Poornima / Dev Deepawali",
    dressCode: "Modest traditional attire; respectful behavior near cremation ghats (Manikarnika & Harishchandra)",
    rating: 4.9,
    reviewsCount: 62000,
    reviews: [
      { user: "Devendra J.", rating: 5, comment: "Witnessing the Maha Aarti from a wooden boat at Dashashwamedh Ghat is a spiritual transcendence." }
    ],
    address: "Dashashwamedh Ghat Rd, Godowlia, Varanasi, Uttar Pradesh 221001",
    lat: 25.3109,
    lng: 83.0104,
    wiki: "https://en.wikipedia.org/wiki/Ghats_in_Varanasi",
    youtube: "https://www.youtube.com/results?search_query=varanasi+ghats+ganga+aarti",
    mapsUrl: "https://maps.google.com/?q=Dashashwamedh+Ghat+Varanasi",
    frequentScams: "Boatmen quoting ₹2000-3000 for regular rides. Negotiate standard government rate (₹300-500 per person) or book via UP Tourism desk. Photography is strictly prohibited at Manikarnika cremation fires.",
    safetyTips: "Watch your footing on mossy ghat stone steps near water edge."
  },
  {
    id: "hawa-mahal",
    name: "Hawa Mahal (Palace of Winds)",
    state: "Rajasthan",
    district: "Jaipur",
    city: "Jaipur",
    tag: "palace",
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Hawa_Mahal_2011.jpg",
    description: "Five-storey pink and red sandstone crown-shaped facade built in 1799 with 953 intricately carved jharokha honeycomb windows.",
    historicalNarrative: "Built by Maharaja Sawai Pratap Singh and designed by Lal Chand Ustad. The honeycomb facade cooled summer breezes through the Venturi effect.",
    hiddenAspect: "The palace has no staircases; floors are connected entirely by gentle ramps designed for palanquins.",
    timings: "09:00 AM - 05:00 PM (Daily)",
    crowdDensity: "High around midday; beautiful golden glow at sunrise",
    dressCode: "Casual comfortable attire",
    rating: 4.8,
    reviewsCount: 38000,
    reviews: [
      { user: "Priya S.", rating: 5, comment: "The rooftop cafe opposite Hawa Mahal gives the iconic postcard view with morning tea!" }
    ],
    address: "Hawa Mahal Rd, Badi Choupad, J.D.A. Market, Jaipur, Rajasthan 302002",
    lat: 26.9239,
    lng: 75.8267,
    wiki: "https://en.wikipedia.org/wiki/Hawa_Mahal",
    youtube: "https://www.youtube.com/results?search_query=hawa+mahal+jaipur+history",
    mapsUrl: "https://maps.google.com/?q=Hawa+Mahal+Jaipur",
    frequentScams: "Street gemstone and jewelry shops claiming government certification. Always ask for GIA/IGI laboratory certs.",
    safetyTips: "Narrow interior corridors and steep ramps; wear non-slip footwear."
  },
  {
    id: "meenakshi-temple",
    name: "Madurai Meenakshi Sundareswarar Temple",
    state: "Tamil Nadu",
    district: "Madurai",
    city: "Madurai",
    tag: "temple",
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Meenakshi_Amman_Temple%2C_Madurai.JPG",
    description: "Historic 2500-year-old temple complex dedicated to Goddess Meenakshi featuring 14 colossal gopuram gateway towers adorned with 33,000 painted stucco sculptures.",
    historicalNarrative: "Centerpiece of ancient Madurai laid out in concentric lotus squares per traditional Vastu Shastra. Expanded by Nayak kings in the 16th-17th century.",
    hiddenAspect: "The Hall of Thousand Pillars contains musical stone pillars tuned to melodic ragas, and the sacred Golden Lotus tank.",
    timings: "05:00 AM - 12:30 PM & 04:00 PM - 10:00 PM",
    crowdDensity: "Very High during Chithirai Festival (April/May)",
    dressCode: "Traditional South Indian dress code strictly enforced: Dhotis/lungis or formal pants for men; Sarees/Salwars for women.",
    rating: 4.9,
    reviewsCount: 31000,
    reviews: [
      { user: "Karthik R.", rating: 5, comment: "The towering colorful gopurams and the nighttime procession ceremony are deeply moving." }
    ],
    address: "Madurai Main, Madurai, Tamil Nadu 625001",
    lat: 9.9195,
    lng: 78.1193,
    wiki: "https://en.wikipedia.org/wiki/Meenakshi_Temple",
    youtube: "https://www.youtube.com/results?search_query=meenakshi+temple+madurai",
    mapsUrl: "https://maps.google.com/?q=Meenakshi+Temple+Madurai",
    frequentScams: "Cellphones are prohibited inside temple; only use official temple cloakroom counters near East Gopuram.",
    safetyTips: "Leave leather belts and bags in your hotel room."
  },
  {
    id: "kerala-backwaters",
    name: "Alappuzha (Alleppey) Venetian Backwaters",
    state: "Kerala",
    district: "Alappuzha",
    city: "Alappuzha",
    tag: "nature",
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Alappuzha_Boat_Beauty_W.jpg",
    description: "Serene labyrinth of palm-fringed lagoons, emerald paddy fields below sea level, and luxury kettuvallam houseboats.",
    historicalNarrative: "Traditional kettuvallam boats were originally constructed using anjili wood without a single nail, tied together with coir ropes to transport spices and rice.",
    hiddenAspect: "Kuttanad is one of the few places on earth where farming is conducted 4 to 10 feet below mean sea level.",
    timings: "Houseboat check-in: 12:00 PM; Day cruises: 09:00 AM - 05:30 PM",
    crowdDensity: "High during Nehru Trophy Boat Race in August & winter peak",
    dressCode: "Light breathable cottons and sandals",
    rating: 4.9,
    reviewsCount: 29000,
    reviews: [
      { user: "Aathira N.", rating: 5, comment: "Drifting along canals with freshly prepared Karimeen Pollichathu fish fry and coconut water is heaven on earth." }
    ],
    address: "Finishing Point, Alappuzha, Kerala 688013",
    lat: 9.4981,
    lng: 76.3388,
    wiki: "https://en.wikipedia.org/wiki/Kerala_backwaters",
    youtube: "https://www.youtube.com/results?search_query=kerala+backwaters+alleppey",
    mapsUrl: "https://maps.google.com/?q=Alleppey+Backwaters+Kerala",
    frequentScams: "Unregistered broker agents at bus station offering sub-standard houseboats without generator or AC backups. Always inspect boat license and safety certificates.",
    safetyTips: "Wear life jackets when on open boat deck; avoid swimming in deep backwater channels."
  },
  {
    id: "red-fort",
    name: "Red Fort (Lal Qila) & Diwan-i-Khas",
    state: "Delhi",
    district: "Central Delhi",
    city: "Delhi",
    tag: "monument",
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Red_Fort_in_Delhi_03-2016_img3.jpg",
    description: "Magnificent red sandstone imperial bastion built in 1638 by Mughal Emperor Shah Jahan, symbol of Indian national sovereignty.",
    historicalNarrative: "Center of Mughal governance for two centuries. Seat where the Prime Minister hoists the Indian Tricolour every Independence Day from the Lahori Gate ramparts.",
    hiddenAspect: "The stream of paradise ('Nahr-i-Bihisht') that once channeled water through the royal marble apartments with fragrant rose water fountains.",
    timings: "09:30 AM - 04:30 PM (Closed Mondays)",
    crowdDensity: "High on weekends and public holidays",
    dressCode: "Casual comfortable attire; sun protection",
    rating: 4.7,
    reviewsCount: 48000,
    reviews: [
      { user: "Nitin B.", rating: 5, comment: "The light and sound evening show narrates Indian history with moving acoustic effects." }
    ],
    address: "Netaji Subhash Marg, Lal Qila, Chandni Chowk, New Delhi, Delhi 110006",
    lat: 28.6562,
    lng: 77.2410,
    wiki: "https://en.wikipedia.org/wiki/Red_Fort",
    youtube: "https://www.youtube.com/results?search_query=red+fort+delhi+documentary",
    mapsUrl: "https://maps.google.com/?q=Red+Fort+Delhi",
    frequentScams: "Uncertified guides at Chandni Chowk metro gate. Hire only ASI certified guides carrying identity badges.",
    safetyTips: "Heavy bag checking at entrance; luggage cloakroom available near ticket plaza."
  },
  {
    id: "konark-sun-temple",
    name: "Konark Sun Temple (Black Pagoda)",
    state: "Odisha",
    district: "Puri",
    city: "Konark",
    tag: "monument",
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Sun_Temple_Konark_Puri_District_Odisha.jpg",
    description: "13th-century UNESCO architectural colossus conceived as a gigantic 24-wheeled chariot of Surya the Sun God pulled by seven spirited stone horses.",
    historicalNarrative: "Constructed by King Narasimhadeva I of the Eastern Ganga Dynasty in 1250 CE. Each 10ft wheel functions as an astronomical sundial telling exact local time down to minutes.",
    hiddenAspect: "The 24 carved stone wheels encode solar shadow dials where the spokes indicate the exact prahar (3-hour division of the day).",
    timings: "06:00 AM - 08:00 PM (Daily)",
    crowdDensity: "High during winter and Konark Dance Festival in December",
    dressCode: "Respectful casual wear",
    rating: 4.8,
    reviewsCount: 22000,
    reviews: [
      { user: "Biswajit P.", rating: 5, comment: "The precision of the sundial wheel is mind-blowing! Our guide showed us how the shadow gave exact time to the minute." }
    ],
    address: "Konark, Puri District, Odisha 752111",
    lat: 19.8876,
    lng: 86.0945,
    wiki: "https://en.wikipedia.org/wiki/Konark_Sun_Temple",
    youtube: "https://www.youtube.com/results?search_query=konark+sun+temple+sundial",
    mapsUrl: "https://maps.google.com/?q=Konark+Sun+Temple+Odisha",
    frequentScams: "Sellers pushing plastic stone replica souvenirs claiming they contain magnetic iron core.",
    safetyTips: "Stay on boardwalk pathways; climbing on ancient carved plinths is punishable by law."
  },
  {
    id: "golden-temple-amritsar",
    name: "Sri Harmandir Sahib (Golden Temple)",
    state: "Punjab",
    district: "Amritsar",
    city: "Amritsar",
    tag: "spiritual",
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Harmandir_Sahib(Golden_Temple).JPG",
    description: "The holiest Gurdwara of Sikhism overlaid with pure gold leaf, standing in the center of the sacred Amrit Sarovar nectar pool.",
    historicalNarrative: "Founded in 1577 by Guru Ram Das. The Guru Granth Sahib was first installed here in 1604 by Guru Arjan Dev. Serves free hot satvik meals to 100,000 pilgrims daily in the world's largest community kitchen (Langar).",
    hiddenAspect: "Designed with four open entrances welcoming all humans regardless of religion, caste, gender, or nationality.",
    timings: "Open 24 hours (Palki Sahib ceremony at 04:30 AM & 10:00 PM)",
    crowdDensity: "High around evening aarti and Gurpurab celebrations",
    dressCode: "Heads must remain covered with cloth/rumal; shoes and socks deposited at free counters; wash feet in running water basin before stepping inside.",
    rating: 5.0,
    reviewsCount: 89000,
    reviews: [
      { user: "Gurpreet S.", rating: 5, comment: "The peace and spiritual glow when looking at the Golden Temple reflecting in the holy Sarovar at night is divine." }
    ],
    address: "Golden Temple Rd, Atta Mandi, Katra Ahluwalia, Amritsar, Punjab 143006",
    lat: 31.6200,
    lng: 74.8765,
    wiki: "https://en.wikipedia.org/wiki/Golden_Temple",
    youtube: "https://www.youtube.com/results?search_query=golden+temple+amritsar+langar",
    mapsUrl: "https://maps.google.com/?q=Golden+Temple+Amritsar",
    frequentScams: "Unauthorized vendors outside selling low quality headscarves for inflated rates (free headscarves are provided at the entrance).",
    safetyTips: "Keep hands dry when carrying prasad; marble walkways are cooled with water mats."
  },
  {
    id: "taj-mahal",
    name: "Taj Mahal",
    state: "Uttar Pradesh",
    district: "Agra",
    city: "Agra",
    tag: "monument",
    image: "https://images.unsplash.com/photo-1564507592333-c60657eea523?w=800&auto=format&fit=crop&q=80",
    description: "A white marble mausoleum built by Shah Jahan in memory of Mumtaz Mahal — an eternal Wonder of the World.",
    historicalNarrative: "Commissioned in 1632 by Mughal Emperor Shah Jahan. Built using translucent Makrana white marble inlaid with 28 varieties of precious and semi-precious stones (pietra dura). Completed by 20,000 artisans over 22 years.",
    hiddenAspect: "A series of sealed subterranean chambers beneath the marble plinth along the Yamuna River bank was designed to regulate subterranean moisture and stabilize the deep sal-wood well foundations.",
    timings: "30 minutes before sunrise to 30 minutes before sunset (Closed on Fridays)",
    crowdDensity: "High at sunrise; Extremely High between 11:00 AM and 04:00 PM",
    dressCode: "Modest casual attire; shoe covers required on main marble mausoleum terrace",
    rating: 4.9,
    reviewsCount: 52000,
    reviews: [
      { user: "Elena D.", rating: 5, comment: "Sunrise at Taj Mahal changed my perspective on architecture forever. The symmetry and delicate marble inlays are miraculous." }
    ],
    address: "Dharmapuri, Forest Colony, Tajganj, Agra, Uttar Pradesh 282001",
    lat: 27.1751,
    lng: 78.0421,
    wiki: "https://en.wikipedia.org/wiki/Taj_Mahal",
    youtube: "https://www.youtube.com/results?search_query=taj+mahal+documentary",
    mapsUrl: "https://maps.google.com/?q=Taj+Mahal+Agra",
    frequentScams: "Aggressive photographers promising 'instant queue skip' or demanding exorbitant prints; unlicensed guides selling fake marble souvenirs made of alabaster or soapstone.",
    safetyTips: "Carry only small wallet and camera; large bags, tripods, drones, and food items are prohibited past security scanners."
  },
  {
    id: "hampi",
    name: "Hampi Group of Monuments (Vijayanagara Empire)",
    state: "Karnataka",
    district: "Vijayanagara / Bellary",
    city: "Hampi",
    tag: "ruins",
    image: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=800&auto=format&fit=crop&q=80",
    description: "UNESCO World Heritage wonderland of the 14th-century Vijayanagara Empire sprawled across surreal boulder-strewn hills.",
    historicalNarrative: "Capital of the opulent Vijayanagara Empire from 1336 to 1565 CE. Medieval chroniclers from Portugal and Persia recorded it as one of the richest metropolises on earth, trading rubies and diamonds by the basket in open street bazaars.",
    hiddenAspect: "The Vittala Temple's 56 Musical Pillars (SaReGaMa pillars) emit distinct musical notes when tapped. The subterranean Shiva temple remains flooded year-round by natural underground springs.",
    timings: "06:00 AM - 06:00 PM (Virupaksha Temple remains open for morning aarti)",
    crowdDensity: "Moderate on weekdays; High during winter season (Nov - Feb)",
    dressCode: "Comfortable trekking gear and hats; remove shoes when entering active temples",
    rating: 4.9,
    reviewsCount: 14500,
    reviews: [
      { user: "Aditya S.", rating: 5, comment: "Like stepping into a mythical boulder kingdom. The stone chariot and sunset from Matanga Hill are unforgettable." }
    ],
    address: "Hampi, Vijayanagara District, Karnataka 583239",
    lat: 15.3350,
    lng: 76.4600,
    wiki: "https://en.wikipedia.org/wiki/Hampi",
    youtube: "https://www.youtube.com/results?search_query=hampi+ruins+history",
    mapsUrl: "https://maps.google.com/?q=Hampi+Karnataka",
    frequentScams: "Moped and scooter rental shops claiming damage scratches that were already present. Always take a clear 360-degree video of any rented scooter before leaving the shop.",
    safetyTips: "Boulders get intensely hot in midday sun. Always carry 2L of water and wear UV protection."
  }
];
